In [1]:
import numpy as np
import sys

def gsMethod(A, b, xn):
    # Inputs: A, b, xn
    # Outputs: xnp1
    N = len(xn)
    xnp1 = np.zeros(xn.shape)
    for j in range(0, N):
        sum = 0
        for k in range(0, N):
            if k < j:
                sum = sum + A[j, k]*xnp1[k]
            elif k > j:
                sum = sum + A[j, k]*xn[k]
        xnp1[j] = (b[j] - sum)/A[j, j]
    return xnp1


#x1 = np.array([7, 9, 3, 10, 6])
#x2 = np.array([-3,1,-1,-4])
#x3 = np.array([-3,1,-1,-4])
#x4 = np.diag(x1, 0)
#x5 = np.diag(x2, 1)
#x6 = np.diag(x3,-1)

A = np.array([[2,-1,0],[-1,4,2],[0,2,6]])

xn = np.array([0,0,0])

xn1 = xn

b = np.array([[-1],[3],[5]])

counter = 0

# gs method
for i in range(sys.maxsize):
    xn = gsMethod(A, b, xn)
    counter += 1
    if(np.linalg.norm((xn1 - xn), np.inf) < 5*10**-6):
        break
    xn1 = xn
print(np.array2string(xn, formatter={'float_kind': '{0:.7f}'.format}))
print(counter)

[-0.0903222 0.1225808 1.6258064]
9


In [2]:
import numpy as np
import sys

# Do one step of Jacobi's method.
def jacobi(A, b, xn):
    # Inputs: A, b, xn
    # Outputs: xnp1
    N = len(xn)
    xnp1 = np.zeros(xn.shape)
    for j in range(0, N):
        sum = 0
        for k in range(0, N):
            if k != j:
                sum = sum + A[j, k]*xn[k]
        xnp1[j] = (b[j] - sum)/A[j, j]
    return xnp1

#x1 = np.array([7, 9, 3, 10, 6])
#x2 = np.array([-3,1,-1,-4])
#x3 = np.array([-3,1,-1,-4])
#x4 = np.diag(x1, 0)
#x5 = np.diag(x2, 1)
#x6 = np.diag(x3,-1)

A = np.array([[2,-1,0],[-1,4,2],[0,2,6]])

xn = np.array([0,0,0])

xn1 = xn

b = np.array([[-1],[3],[5]])

counter = 0

# jacobi method
for i in range(sys.maxsize):
    xn = jacobi(A, b, xn)
    counter += 1
    if(np.linalg.norm((xn1 - xn), np.inf) < 5*10**-6):
        break
    xn1 = xn
print(np.array2string(xn, formatter={'float_kind': '{0:.7f}'.format}))
print(counter)

[-0.3529418 0.2941197 0.7352946]
21


In [2]:
import numpy as np
import sys

def sor(A, b, xn, w):
    # Inputs: A, b, xn
    # Outputs: xnp1
    N = len(xn)
    xnp1 = np.zeros(xn.shape)
    for j in range(0, N):
        sum = 0
        for k in range(0, N):
            if k < j:
                sum = sum + A[j, k]*xnp1[k]
            elif k > j:
                sum = sum + A[j, k]*xn[k]

        xnp1[j] = w*(b[j] - sum)/A[j, j] + (1-w)*xn[j]
    return xnp1


x1 = np.array([7, 9, 3, 10, 6])
x2 = np.array([-3,1,-1,-4])
x3 = np.array([-3,1,-1,-4])
x4 = np.diag(x1, 0)
x5 = np.diag(x2, 1)
x6 = np.diag(x3,-1)

A = x4 + x5 + x6

xn = np.array([0,0,0,0,0])

xn1 = xn

b = np.array([[1],[18],[7], [17], [14]])

counter = 0

# SOR method
for i in range(10):
    xn = sor(A, b, xn, 1/2)
    counter += 1
    #if(np.linalg.norm((xn1 - xn), np.inf) < 5*10**-6):
    #    break
    xn1 = xn
print(np.array2string(xn, formatter={'float_kind': '{0:.7f}'.format}))
print(counter)

[1.0040993 2.0251355 2.8513108 3.7985695 4.7900050]
10
