In [2]:
import numpy as np
import sys

# Do one step of Jacobi's method.
def dojacobi(A, b, xn):
    # Inputs: A, b, xn
    # Outputs: xnp1
    N = len(xn)
    xnp1 = np.zeros(xn.shape)
    for j in range(0, N):
        sum = 0
        for k in range(0, N):
            if k != j:
                sum = sum + A[j, k]*xn[k]
        xnp1[j] = (b[j] - sum)/A[j, j]
    return xnp1


def dojacobiMod(A, b, xn):
    # Inputs: A, b, xn
    # Outputs: xnp1
    N = len(xn)
    xnp1 = np.zeros(xn.shape)
    for j in range(0, N):
        sum = 0
        for k in range(0, N):
            if k < j:
                sum = sum + A[j, k]*xnp1[k]
            elif k > j:
                sum = sum + A[j, k]*xn[k]
        xnp1[j] = (b[j] - sum)/A[j, j]
    return xnp1


x1 = np.array([7, 9, 3, 10, 6])
x2 = np.array([-3,1,-1,-4])
x3 = np.array([-3,1,-1,-4])
x4 = np.diag(x1, 0)
x5 = np.diag(x2, 1)
x6 = np.diag(x3,-1)

print(x4)

A = x4 + x5 + x6

print(A)

xn = np.array([0,0,0,0,0])

b = np.array([[1],[18],[7],[17],[14]])

for i in range(20):
    xn = dojacobiMod(A, b, xn)
    xn1 = xn

print(xn1)

[[ 7  0  0  0  0]
 [ 0  9  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0  6]]
[[ 7 -3  0  0  0]
 [-3  9  1  0  0]
 [ 0  1  3 -1  0]
 [ 0  0 -1 10 -4]
 [ 0  0  0 -4  6]]
[1. 2. 3. 4. 5.]
